### ISSUE TITLE
colorisation syntaxique pour les blocs de code

### ISSUE THREAD

**Issue by tbenett** [lelionvert/blog-articles#15]
_Originally posted by @tbenett in https://github.com/lelionvert/blog/pull/12#issuecomment-594436020_

Par défaut la colorisation syntaxique des code blocks est désactivé avec `markdown-it`, le parser markdown que l'on utilise. 

Exemple : 

<pre>
```java
class Name { ... }
```
</pre>

sera interprété correctement par `markdown-it` mais restera monochrome.

On aimerait changer cela afin d'avoir de jolis code blocks tout plein de couleurs

**Comment by tbenett** [comment]
Une des pistes se trouve dans la configuration du plugin qui fait appel à `markdown-it` : 

https://hmsk.github.io/frontmatter-markdown-loader/options.html#configure-markdown-it

et là

https://github.com/markdown-it/markdown-it#init-with-presets-and-options

**Comment by MaximeRnR** [comment]
Résolu dans #12 

J'ai suivi la doc de https://hmsk.github.io/frontmatter-markdown-loader/options.html#configure-markdown-it 

j'ai ajouté `highlight.js` ( qui est dans la dépendance `@nuxtjs/markdown-it` ) 
j'ai over-ride la fonction highlight de `markdown-it` 

j'ai ajouté la style sheet qui m’intéresse dans ̀Article.vue`

J'ai choisi le css `github-gist` arbitrairement.

[Les choix possibles ici](https://github.com/highlightjs/highlight.js/tree/master/src/styles)

**Comment by tbenett** [comment]
Merci ! 

Je bloque sur un truc cependant, je ne comprends pas pourquoi il y a besoin de rajouter le CSS dans le`article.vue`. Je m'attendrais à ce qu'il vienne avec le dépendance `highlight.js` en fait et soit traité par les différents loaders.

Pourquoi n'est-ce pas le cas ?

**Comment by MaximeRnR** [comment]
> Merci !
> 
> Je bloque sur un truc cependant, je ne comprends pas pourquoi il y a besoin de rajouter le CSS dans le`article.vue`. Je m'attendrais à ce qu'il vienne avec le dépendance `highlight.js` en fait et soit traité par les différents loaders.
> 
> Pourquoi n'est-ce pas le cas ?

J'm'attendais à ça aussi. Mais je n'ai pas de réponse.

**Comment by bachrc** [comment]
Peut-être pourrions avoir un indice @ismailnguyen ? :)

**Comment by MaximeRnR** [comment]
J'ai changé j'utilise le cdn dans le article.vue j'ai rajouté un fichier css dans la conf de nuxtjs. Je trouve ça plus propre.
