### ISSUE TITLE
programmation de la publication

### ISSUE THREAD

**Issue by tbenett** [lelionvert/blog-articles#4]
Un **PUBLISHER** souhaite pouvoir programmer la publication d'un article.

Par exemple : 

Je suis un PUBLISHER qui termine la review d'un article à 16h00. Je veux pouvoir faire en sorte que cet article soit publié sur le blog, le lendemain à 8h00 quand tout le monde est dans les transports publics. 

Sujet en discussion puisqu'il n'est pas encore déterminé si c'est la publication ou bien le relai dans les médias (linkedin, twitter, ...) qui est préférable. 

---

Une solution envisageable est de permettre, via une UI (qqpart) de faire un merge via un cron...

**Comment by ismailnguyen** [comment]
Il est possible de faire plus simple, il suffit que la personne qui rédige l'article mette une date de publication postérieur (la date de publication finale), et dans la page d'accueil n'afficher seulement les articles dont la date de publication est dépassée ;)
