### ISSUE TITLE
Feature: Partage article sur LinkedIn

### ISSUE THREAD

**Issue by QuaintMako** [lelionvert/blog-articles#50]
On souhaite pouvoir partager un article du blog en passant sur LinkedIn.

S'inspirer de l'existant bouton pour partager sur Twitter.

**Comment by ismailnguyen** [comment]
Hello @QuaintMako,

Il suffit pour cela de reproduire le composant TwitterShareLink (https://github.com/lelionvert/blog-articles/blob/master/components/twitterShareLink.vue), en remplaçant l'icone Twitter (class css fa-twitter, par la class css fa-linkedin, puis de renommer la fonction twitterShareUrl par linkedinShareUrl et son contenu par le suivant :
```Javascript
 return 'https://www.linkedin.com/shareArticle?mini=true'
                + '&url=' + this.articleUrl
                + '&title=' + this.article.title
                + '&source=https://blog-lclv.vercel.app/';
```

**Comment by QuaintMako** [comment]
@ismailnguyen merci pour la piste, j'étais effectivement partie dessus!

Pour le moment, je me bats avec de la compilation Vercel qui n'est pas très bavarde quant à ses problèmes.
